-- --versao --1
SELECT
TP_FORNE, --integer
DESCRICAO, --text
TIPO_AGRUPADOR, --integer
COD_AGRUPADOR, --integer
FROM
    supr_130

-- versao 2 Tipo Fornecedor PADRAO
SELECT
    TP_FORNE AS TIPO_FORNECEDOR,
    DESCRICAO,
    TIPO_AGRUPADOR,
    COD_AGRUPADOR AS CODIGO_AGRUPADOR
FROM
    supr_130