-- versao 1
SELECT
    NIVEL_ESTRUTURA, --texttext
    REFERENCIA, --text
    DESCR_REFERENCIA, --text
    UNIDADE_MEDIDA, --text
    PERC_2_QUALIDADE, --floatid
    COLECAO, --integer, 
    CONTA_ESTOQUE, --integer
    LINHA_PRODUTO, --integer
    ARTIGO, --integer
    ARTIGO_COTAS, --integer
    ARTIGO_APROVEIT, --integer
    PERCENT_DESCONTO, --float
    TIPO_PRODUTO, --integer
    VARIACAO_CORES, --integer
    TAMANHO_FILME, --integer
    RAPORTAGEM, --float
    PERCENT_PERDA_1, --float
    PERCENT_PERDA_2, --float
    PERCENT_PERDA_3, --float
    APROVEIT_MEDIO, --float
    METROS_LINEARES, --float
    INDICE_REAJUSTE, --float
    ITEM_BAIXA_ESTQ, --text
    DEMANDA, --integer
    PONTOS_POR_CM, --integer
    OBSERVACAO, --text
    AGULHAS_FALHADAS, --integer
    FORMACAO_AGULHAS, --integer
    CLASSIFIC_FISCAL, --text
    COMPRADO_FABRIC, --integer
    ABERTO_TUBULAR, --integer
    NUMERO_ROTEIRO, --integer
    REF_ORIGINAL, --text
    NUMERO_MOLDE, --text
    COR_DE_ESTOQUE, --text
    DIV_PROD, --integer
    COR_DE_PRODUCAO, --text
    CODIGO_CONTABIL, --integer
    CGC_CLIENTE_2, --integer
    CGC_CLIENTE_4, --integer
    CGC_CLIENTE_9, --integer
    COMPOSICAO_01, --text
    COMPOSICAO_02, --text
    COMPOSICAO_03, --text
    COMPOSICAO_04, --text
    COMPOSICAO_05, --text
    PERC_COMPOSICAO1, --float
    PERC_COMPOSICAO2, --float
    PERC_COMPOSICAO3, --float
    PERC_COMPOSICAO4, --float
    PERC_COMPOSICAO5, --float
    ESTAGIO_ALTERA_PROGRAMADO, --integer
    RISCO_PADRAO, --integer
    RESPONSAVEL, --text
    MULTIPLICADOR, --integer
    NUM_SOL_DESENV, --text
    SORTIMENTO_DIVERSOS, --text
    GRUPO_AGRUPADOR, --text
    SUB_AGRUPADOR, --text
    COD_EMBALAGEM, --integer
    CONF_ALTERA_PROG, --integer
    OBSERVACAO2, --text
    OBSERVACAO3, --text
    PUBLICO_ALVO, --integer
    COR_DE_SORTIDO, --text
    TIPO_CODIGO_EAN, --integer
    NUM_PROGRAMA, --text
    REFERENCIA_DESENV, --text
    TAB_RENDIMENTO, --integer
    LARGURA_CILINDRO, --float
    LARGURA_ESTAMPA, --float
    DESCRICAO_TAG1, --text
    DESCRICAO_TAG2, --text
    DESCR_COMPLEMENTAR, --text
    PASTA_BANHO, --integer
    PERIMETRO_CORTE, --float
    PRODUTO_PROTOTIPO, --text
    TEMPO_LASER, --float
    COLECAO_CLIENTE, --text
    DESCR_INGLES, --text
    DESCR_ESPANHOL, --text
    TAMANHO_AMOSTRA, --text
    PESO_AMOSTRA, --float
    COMP_SERRA_FITA, --text
    PARTE_COMPOSICAO_01, --text
    PARTE_COMPOSICAO_02, --text
    PARTE_COMPOSICAO_03, --text
    PARTE_COMPOSICAO_04, --text
    PARTE_COMPOSICAO_05, --text
    COMPOSICAO_01_INGLES, --text
    COMPOSICAO_02_INGLES, --text
    COMPOSICAO_03_INGLES, --text
    COMPOSICAO_04_INGLES, --text
    COMPOSICAO_05_INGLES, --text
    TIPO_ESTAMPA, --integer
    IMP_INF_EMPRESA_TAG, --text
    ESTAMPA_IMPRESSA, --integer
    COD_TIPO_AVIAMENTO, --text
    COD_ATRIBUTO_01, --integer
    COD_ATRIBUTO_02, --integer
    COD_ATRIBUTO_03, --integer
    COD_ATRIBUTO_04, --integer
    COD_ATRIBUTO_05, --integer
    COD_ATRIBUTO_06, --integer
    COD_ATRIBUTO_07, --integer
    COD_ATRIBUTO_08, --integer
    COD_ATRIBUTO_09, --integer
    COD_ATRIBUTO_10, --integer
    REFERENCIA_AGRUPADOR, --text
    MAQUINA_PILOTO, --text
    FINURA_PILOTO, --text
    GRADUACAO_PILOTO, --text
    PROGRAMA_PILOTO, --text
    PROGRAMADOR_PILOTO, --text
    PESO_BRUTO_PILOTO, --float
    PESO_ACABAMENTO_PILOTO, --float
    TECELAGEM_PILOTO, --text
    FACCAO_PILOTO, --text
    PERS_BORDADO_PILOTO, --integer
    PERS_LAVACAO_PILOTO, --integer
    PERS_SERIGRAFIA_PILOTO, --integer
    GRUPO_TECIDO_CORTE, --integer
    PERSONALIZACAO_PILOTO, --text
    DATA_MOV_CILINDRO, --atetime
    SERIE_TAMANHO, --integer
    NUMERO_PONTOS_LASER, --integer
    PERCENTUAL_AMACIANTE, --float
    SIMBOLO_1, --text
    SIMBOLO_2, --text
    SIMBOLO_3, --text
    SIMBOLO_4, --text
    SIMBOLO_5, --text
    LOTE_ESTOQUE, --integer
    DIAS_MATURACAO, --integer
    COD_BAR_POR_CLI, --text
    FAMILIA_ATRIBUTO, --text
    DOC_REFERENCIAL, --text
    LIGAMENTO, --text
    PERC_COMPOSICAO6, --float
    PERC_COMPOSICAO7, --float
    PERC_COMPOSICAO8, --float
    PERC_COMPOSICAO9, --float
    PERC_COMPOSICAO10, --float
    COMPOSICAO_06, --text
    COMPOSICAO_07, --text
    COMPOSICAO_08, --text
    COMPOSICAO_09, --text
    COMPOSICAO_10, --text
    SIMBOLO_6, --text
    SIMBOLO_7, --text
    SIMBOLO_8, --text
    SIMBOLO_9, --text
    SIMBOLO_10, --text
    PARTE_COMPOSICAO_06, --text
    PARTE_COMPOSICAO_07, --text
    PARTE_COMPOSICAO_08, --text
    PARTE_COMPOSICAO_09, --text
    PARTE_COMPOSICAO_10, --text
    PRODUTO_VENDA, --text
    NVLPRECOMONTAGEM, --float
    OPCAO_VENDA_COR, --integer
    ULTIMA_COR_SORTIDA, --text
    TIPO_TAG_EAN, --text
    MODULAR, --integer
    FORMA_MOLDE, --text
    TAMANHO_ABA, --float
    COSTURA_ABA, --text
    ENGOMACAO, --text
    CAIXAS, --text
    ORIGEM_MERCADORIA, --integer
    TOMBAMENTO_ABA, --text
    IND_ENVIA_INFOTINT, --text
    CEST, --text
    ORIGEM_PRECO_CUSTO, --text
    PARTE_CONJUNTO_01, --integer
    PARTE_CONJUNTO_02, --integer
    PARTE_CONJUNTO_03, --integer
    PARTE_CONJUNTO_04, --integer
    PARTE_CONJUNTO_05, --integer
    PARTE_CONJUNTO_06, --integer
    PARTE_CONJUNTO_07, --integer
    PARTE_CONJUNTO_08, --integer
    PARTE_CONJUNTO_09, --integer
    PARTE_CONJUNTO_10, --integer
    STATUS_AGULHEIRO, --integer
    TIPO_PROCESSO, --text
    COMPOSICAO_01_ESPANHOL, --text
    COMPOSICAO_02_ESPANHOL, --text
    COMPOSICAO_03_ESPANHOL, --text
    COMPOSICAO_04_ESPANHOL, --text
    COMPOSICAO_05_ESPANHOL, --text
    COMPOSICAO_06_ESPANHOL, --text
    COMPOSICAO_07_ESPANHOL, --text
    COMPOSICAO_08_ESPANHOL, --text
    COMPOSICAO_09_ESPANHOL, --text
    COMPOSICAO_10_ESPANHOL, --text
    COMPOSICAO_06_INGLES, --text
    COMPOSICAO_07_INGLES, --text
    COMPOSICAO_08_INGLES, --text
    COMPOSICAO_09_INGLES, --text
    COMPOSICAO_10_INGLES, --text
FROM 
    basi_030

--versao 2 LISTAGEM DE GRUPO DE PRODUTOS_PADRÃO
SELECT
    NIVEL_ESTRUTURA, 
    REFERENCIA, 
    DESCR_REFERENCIA, 
    UNIDADE_MEDIDA, 
    PERC_2_QUALIDADE, id
    COLECAO, , query_ );
    CONTA_ESTOQUE, 
    LINHA_PRODUTO, 
    ARTIGO, 
    ARTIGO_COTAS, 
    ARTIGO_APROVEIT, 
    PERCENT_DESCONTO, 
    TIPO_PRODUTO, 
    VARIACAO_CORES, 
    TAMANHO_FILME, 
    RAPORTAGEM, 
    PERCENT_PERDA_1, 
    PERCENT_PERDA_2, 
    PERCENT_PERDA_3, 
    APROVEIT_MEDIO, 
    METROS_LINEARES, 
    INDICE_REAJUSTE, 
    ITEM_BAIXA_ESTQ, 
    DEMANDA, 
    PONTOS_POR_CM, 
    OBSERVACAO, 
    AGULHAS_FALHADAS, 
    FORMACAO_AGULHAS, 
    CLASSIFIC_FISCAL, 
    COMPRADO_FABRIC, 
    ABERTO_TUBULAR, 
    NUMERO_ROTEIRO, 
    REF_ORIGINAL, 
    NUMERO_MOLDE, 
    COR_DE_ESTOQUE, 
    DIV_PROD, 
    COR_DE_PRODUCAO, 
    CODIGO_CONTABIL, 
    CGC_CLIENTE_2, 
    CGC_CLIENTE_4, 
    CGC_CLIENTE_9, 
    COMPOSICAO_01, 
    COMPOSICAO_02, 
    COMPOSICAO_03, 
    COMPOSICAO_04, 
    COMPOSICAO_05, 
    PERC_COMPOSICAO1, 
    PERC_COMPOSICAO2, 
    PERC_COMPOSICAO3, 
    PERC_COMPOSICAO4, 
    PERC_COMPOSICAO5, 
    ESTAGIO_ALTERA_PROGRAMADO, 
    RISCO_PADRAO, 
    RESPONSAVEL, 
    MULTIPLICADOR, 
    NUM_SOL_DESENV, 
    SORTIMENTO_DIVERSOS, 
    GRUPO_AGRUPADOR, 
    SUB_AGRUPADOR, 
    COD_EMBALAGEM, 
    CONF_ALTERA_PROG, 
    OBSERVACAO2, 
    OBSERVACAO3, 
    PUBLICO_ALVO, 
    COR_DE_SORTIDO, 
    TIPO_CODIGO_EAN, 
    NUM_PROGRAMA, 
    REFERENCIA_DESENV, 
    TAB_RENDIMENTO, 
    LARGURA_CILINDRO, 
    LARGURA_ESTAMPA, 
    DESCRICAO_TAG1, 
    DESCRICAO_TAG2, 
    DESCR_COMPLEMENTAR, 
    PASTA_BANHO, 
    PERIMETRO_CORTE, 
    PRODUTO_PROTOTIPO, 
    TEMPO_LASER, 
    COLECAO_CLIENTE, 
    DESCR_INGLES, 
    DESCR_ESPANHOL, 
    TAMANHO_AMOSTRA, 
    PESO_AMOSTRA, 
    COMP_SERRA_FITA, 
    PARTE_COMPOSICAO_01, 
    PARTE_COMPOSICAO_02, 
    PARTE_COMPOSICAO_03, 
    PARTE_COMPOSICAO_04, 
    PARTE_COMPOSICAO_05, 
    COMPOSICAO_01_INGLES, 
    COMPOSICAO_02_INGLES, 
    COMPOSICAO_03_INGLES, 
    COMPOSICAO_04_INGLES, 
    COMPOSICAO_05_INGLES, 
    TIPO_ESTAMPA, 
    IMP_INF_EMPRESA_TAG, 
    ESTAMPA_IMPRESSA, 
    COD_TIPO_AVIAMENTO, 
    COD_ATRIBUTO_01, 
    COD_ATRIBUTO_02, 
    COD_ATRIBUTO_03, 
    COD_ATRIBUTO_04, 
    COD_ATRIBUTO_05, 
    COD_ATRIBUTO_06, 
    COD_ATRIBUTO_07, 
    COD_ATRIBUTO_08, 
    COD_ATRIBUTO_09, 
    COD_ATRIBUTO_10, 
    REFERENCIA_AGRUPADOR, 
    MAQUINA_PILOTO, 
    FINURA_PILOTO, 
    GRADUACAO_PILOTO, 
    PROGRAMA_PILOTO, 
    PROGRAMADOR_PILOTO, 
    PESO_BRUTO_PILOTO, 
    PESO_ACABAMENTO_PILOTO, 
    TECELAGEM_PILOTO, 
    FACCAO_PILOTO, 
    PERS_BORDADO_PILOTO, 
    PERS_LAVACAO_PILOTO, 
    PERS_SERIGRAFIA_PILOTO, 
    GRUPO_TECIDO_CORTE, 
    PERSONALIZACAO_PILOTO, 
    DATA_MOV_CILINDRO, atetime
    SERIE_TAMANHO, 
    NUMERO_PONTOS_LASER, 
    PERCENTUAL_AMACIANTE, 
    SIMBOLO_1, 
    SIMBOLO_2, 
    SIMBOLO_3, 
    SIMBOLO_4, 
    SIMBOLO_5, 
    LOTE_ESTOQUE, 
    DIAS_MATURACAO, 
    COD_BAR_POR_CLI, 
    FAMILIA_ATRIBUTO, 
    DOC_REFERENCIAL, 
    LIGAMENTO, 
    PERC_COMPOSICAO6, 
    PERC_COMPOSICAO7, 
    PERC_COMPOSICAO8, 
    PERC_COMPOSICAO9, 
    PERC_COMPOSICAO10, 
    COMPOSICAO_06, 
    COMPOSICAO_07, 
    COMPOSICAO_08, 
    COMPOSICAO_09, 
    COMPOSICAO_10, 
    SIMBOLO_6, 
    SIMBOLO_7, 
    SIMBOLO_8, 
    SIMBOLO_9, 
    SIMBOLO_10, 
    PARTE_COMPOSICAO_06, 
    PARTE_COMPOSICAO_07, 
    PARTE_COMPOSICAO_08, 
    PARTE_COMPOSICAO_09, 
    PARTE_COMPOSICAO_10, 
    PRODUTO_VENDA, 
    NVLPRECOMONTAGEM, 
    OPCAO_VENDA_COR, 
    ULTIMA_COR_SORTIDA, 
    TIPO_TAG_EAN, 
    MODULAR, 
    FORMA_MOLDE, 
    TAMANHO_ABA, 
    COSTURA_ABA, 
    ENGOMACAO, 
    CAIXAS, 
    ORIGEM_MERCADORIA, 
    TOMBAMENTO_ABA, 
    IND_ENVIA_INFOTINT, 
    CEST, 
    ORIGEM_PRECO_CUSTO, 
    PARTE_CONJUNTO_01, 
    PARTE_CONJUNTO_02, 
    PARTE_CONJUNTO_03, 
    PARTE_CONJUNTO_04, 
    PARTE_CONJUNTO_05, 
    PARTE_CONJUNTO_06, 
    PARTE_CONJUNTO_07, 
    PARTE_CONJUNTO_08, 
    PARTE_CONJUNTO_09, 
    PARTE_CONJUNTO_10, 
    STATUS_AGULHEIRO, 
    TIPO_PROCESSO, 
    COMPOSICAO_01_ESPANHOL, 
    COMPOSICAO_02_ESPANHOL, 
    COMPOSICAO_03_ESPANHOL, 
    COMPOSICAO_04_ESPANHOL, 
    COMPOSICAO_05_ESPANHOL, 
    COMPOSICAO_06_ESPANHOL, 
    COMPOSICAO_07_ESPANHOL, 
    COMPOSICAO_08_ESPANHOL, 
    COMPOSICAO_09_ESPANHOL, 
    COMPOSICAO_10_ESPANHOL, 
    COMPOSICAO_06_INGLES, 
    COMPOSICAO_07_INGLES, 
    COMPOSICAO_08_INGLES, 
    COMPOSICAO_09_INGLES, 
    COMPOSICAO_10_INGLES, 


