--tabela de constas a receber systextil: fatu_070 e fatu_075


SELECT 
	Nota_Fiscal AS QtdeDoc,
    Valor AS ValorTotal,
	Vencimento
FROM 
	DBMicrodata.dbo.VW_Rec_DuplicatasEmAberto
WHERE
	Empresa = '01';
	
	
SELECT 
	'001' AS CODIGO_EMPRESA, 
	DA.CNPJ_CPF CLI_DUP_CGC_CLI9, 
	AS CLI_DUP_CGC_CLI4,
	AS CLI_DUP_CGC_CLI2,
	AS TIPO_TITULO,
	AS NUM_DUPLICATA,
	AS SEQ_DUPLICATAS,
	AS DATA_VENC_DUPLIC,
	AS DATA_PRORROGACAO,
	AS DATA_EMISSAO,
	AS PREVISAO,
	AS VALOR_DUPLICATA,
	AS SITUACAO_DUPLIC,
	AS PORTADOR_DUPLIC,
	AS PEDIDO_VENDA,
	AS NR_TITULO_BANCO,
	AS COD_REP_CLIENTE,
	AS POSICAO_DUPLIC,
	AS COD_HISTORICO,
	AS COMPL_HISTORICO,
	AS COD_LOCAL,
	AS MOEDA_TITULO,
	AS VALOR_MOEDA,
	AS COD_TRANSACAO,
	AS CODIGO_CONTABIL,
	AS NUM_CONTABIL,
	AS SALDO_DUPLICATA,
	AS CONTA_CORRENTE,
	AS NUMERO_REMESSA,
	AS PERCENTUAL_COMIS,
	AS VALOR_COMIS,
	AS BASE_CALC_COMIS,
	AS PERC_COMIS_CREC,
	AS TIPO_COMISSAO,
	AS CODIGO_ADMINISTR,
	AS COMISSAO_ADMINISTR,
	AS PERC_COMIS_CREC_ADM,
	AS SEQ_END_COBRANCA,
	AS OBSERVACAO,
	AS CLI9RESPTIT,
	AS CLI4RESPTIT,
	AS CLI2RESPTIT,
	AS COD_FORMA_PAGTO
FROM 
	DBMicrodata.dbo.VW_Rec_DuplicatasEmAberto AS DA
WHERE
	Empresa = '01';	
	
	



GO


