--tabela de contas a receber systextil: fatu_070 
--tabela de contas recebidas systextil: fatu_075 

--vw base do sistema microdata
SELECT 
	Nota_Fiscal AS QtdeDoc,
    Valor AS ValorTotal,
	Vencimento
FROM 
	DBMicrodata.dbo.VW_Rec_DuplicatasEmAberto
WHERE
	Empresa = '01';

--trazendo todos os campos da vw base
SELECT 
	Empresa,
	idDocumento,
	CNPJ_CPF,
	Cliente,
	Nota_Fiscal,
	Serie,
	Desdobro,
	Emissao,
	Vencimento,
	Banco,
	Operacao,
	Valor,
FROM 
	DBMicrodata.dbo.VW_Rec_DuplicatasEmAberto
WHERE
	Empresa = '01';
	
	
SELECT 
	'001' AS CODIGO_EMPRESA, 
	SUBSTRING(REPLACE(REPLACE(REPLACE(DA.CNPJ_CPF,'.',''),'/',''),'-',''),1,8) AS CLI_DUP_CGC_CLI9, 
	SUBSTRING(REPLACE(REPLACE(REPLACE(DA.CNPJ_CPF,'.',''),'/',''),'-',''),9,4) AS CLI_DUP_CGC_CLI4,
	SUBSTRING(REPLACE(REPLACE(REPLACE(DA.CNPJ_CPF,'.',''),'/',''),'-',''),13,2) AS CLI_DUP_CGC_CLI2,
	AS TIPO_TITULO,
	AS NUM_DUPLICATA,
	AS SEQ_DUPLICATAS,
	FORMAT(DA.Vencimento, 'dd/MM/yyyy') AS DATA_VENC_DUPLIC,
	AS DATA_PRORROGACAO,
	FORMAT(DA.Emissao, 'dd/MM/yyyy') AS DATA_EMISSAO,
	AS PREVISAO,
	AS VALOR_DUPLICATA,
	AS SITUACAO_DUPLIC,
	AS PORTADOR_DUPLIC,
	AS PEDIDO_VENDA,
	AS NR_TITULO_BANCO,
	AS COD_REP_CLIENTE,
	AS POSICAO_DUPLIC,
	AS COD_HISTORICO,
	AS COMPL_HISTORICO,
	AS COD_LOCAL,
	0 AS MOEDA_TITULO,
	DA.Valor AS VALOR_MOEDA,
	AS COD_TRANSACAO,
	AS CODIGO_CONTABIL,
	AS NUM_CONTABIL,
	AS SALDO_DUPLICATA,
	AS CONTA_CORRENTE,
	AS NUMERO_REMESSA,
	AS PERCENTUAL_COMIS,
	AS VALOR_COMIS,
	AS BASE_CALC_COMIS,
	AS PERC_COMIS_CREC,
	AS TIPO_COMISSAO,
	AS CODIGO_ADMINISTR,
	AS COMISSAO_ADMINISTR,
	AS PERC_COMIS_CREC_ADM,
	AS SEQ_END_COBRANCA,
	AS OBSERVACAO,
	AS CLI9RESPTIT,
	AS CLI4RESPTIT,
	AS CLI2RESPTIT,
	AS COD_FORMA_PAGTO
FROM 
	DBMicrodata.dbo.VW_Rec_DuplicatasEmAberto AS DA
WHERE
	Empresa = '01';	
	
	



GO


