-- versao 1
SELECT
CODIGO_HISTORICO, --integer
HISTORICO_CONTAB, --text
SINAL_TITULO, --integer
SINAL_DIARIO, --integer
FLUXO, --integer
ENTRADA_SAIDA, --text
SINAL_COMISSAO, --integer
TIPO_HISTORICO, --text
DIARIO, --integer
ATUALIZA_COMIS, --integer
COD_HIST_CONT, --integer
CONTA_CORRENTE, --integer
ATUALIZA_ACC, --integer
MOT_EXCLUSAO_CLI, --integer
INF_CCUSTO, --integer
CONSIDERA_REGIME_CAIXA --text
FROM
  cont_010

-- versao 2
SELECT
CODIGO_HISTORICO, 
HISTORICO_CONTAB,
SINAL_TITULO, 
SINAL_DIARIO,
FLUXO,
ENTRADA_SAIDA,
SINAL_COMISSAO, 
TIPO_HISTORICO, 
DIARIO, 
ATUALIZA_COMIS, 
COD_HIST_CONT, 
CONTA_CORRENTE, 
ATUALIZA_ACC, 
MOT_EXCLUSAO_CLI, 
INF_CCUSTO, 
CONSIDERA_REGIME_CAIXA
FROM
  cont_010