--VER 02
SELECT
    COD_REP_CLIENTE AS CODIGO,
    NOME_REP_CLIENTE AS REPRESENTANTE,
    CGC_9 || CGC_4 || CGC_2 AS CPF_CNPJ, 
    CASE TIPO_REPR
        WHEN 1 THEN '1 - MICRO'
        WHEN 2 THEN '2 - AUTONOMO'
        WHEN 3 THEN '3 - JURIDICA'
        WHEN 4 THEN '4 - ADMINISTRADOR'
        WHEN 5 THEN '5 - VENDEDOR' 
        ELSE 'N/A' 
    END AS TIPO, 
    basi_160.COD_CIDADE || '-' || basi_160.CIDADE AS CIDADE, 
    DDD_CELULAR || '-' || FONE_REP_CLIENTE AS FONE, 
    DDD_CELULAR || '-' || NUMERO_CELULAR AS CELULAR,  
    DDD_CELULAR || '-' || NUMERO_FAX AS FAX,
    E_MAIL AS EMAIL,
    pedi_020.COD_BANCO_REPR || '-' || pedi_050.NOME_BANCO AS BANCO, 
    pedi_020.CODIGO_AGENCIA AS AGENCIA,  
    pedi_020.CONTA_BANCO_REP AS NRCONTA
FROM
   pedi_020
     INNER JOIN basi_160 ON basi_160.COD_CIDADE = pedi_020.COD_CIDADE
     INNER JOIN pedi_050 ON pedi_050 .COD_PORTADOR = pedi_020.COD_BANCO_REPR
ORDER BY
    pedi_020.NOME_REP_CLIENTE ASC



     
    


/**
    OBS: 
        TIPO_REPR -> TABELA DE TIPOS DE REPRESEMTANTE : SUSPEITO QUE NÃO EXISTA UM CASE RESOLVE... MAS SE EXISTIR ME FALA
        COD_CIDADE -> CIDADE + ESTADO : basi_160
        COD_BANCO_REPR -> TABELA DE BANCOS
        SIT_REP_CLIENTE -> TABELA DE SITUAÇÃO DE REPRESENTANTE : SUSPEITO QUE NÃO EXISTA UM CASE RESOLVE... MAS SE EXISTIR ME FALA
    DEV: 
        TIAGO DE ABREU | DATE: 17/02/2022 | COMMIT MESSAGE: INICIANDO RELATÓRIO DE REPRESENTANTES 
**/