
SELECT
    REPRESENTANTES.COD_REP_CLIENTE AS CODIGO, 
    --REPRESENTANTES.TIPO_REPR + ' - ' ?.TIPO AS TIPO, 
    REPRESENTANTES.NOME_REP_CLIENTE AS RAZÃO SOCIAL, 
    REPRESENTANTES.COD_CIDADE + ' - ' + CIDADES.CIDADE AS CIDADE,
    CIDADES.ESTADO, 
    '('+ REPRESENTANTES.DDD_CELULAR +') ' + REPRESENTANTES.FONE_REP_CLIENTE AS FONE, 
    '('+ REPRESENTANTES.DDD_CELULAR +') ' + REPRESENTANTES.NUMERO_CELULAR AS CELULAR,  
    '('+ REPRESENTANTES.DDD_CELULAR +') ' + REPRESENTANTES.NUMERO_FAX AS FAX, 
    REPRESENTANTES.E_MAIL AS EMAIL, 
    REPRESENTANTES.CGC_9 + '/' + REPRESENTANTES.CGC_4 + '-' + REPRESENTANTES.CGC_2 AS CNPJ, 
    REPRESENTANTES.COD_BANCO_REPR, -- + '-' + ?.BANCO AS BANCO, 
    REPRESENTANTES.CODIGO_AGENCIA AS AGENCIA,  
    REPRESENTANTES.CONTA_BANCO_REP AS NRCONTA, 
    REPRESENTANTES.PERC_COMISSAO_VENDA AS COMISSAO 
FROM
   pedi_020 AS REPRESENTANTES
   INNER JOIN basi_160 AS CIDADES IN CIDADES.COD_CIDADE = REPRESENTANTES.COD_CIDADE
   --INNER HOIN ?.BANCO AS BANCOS IN BANCOS.COD_BANCO = REPRESENTANTES.COD_BANCO_REPR
WHERE
    REPRESENTANTES.SIT_REP_CLIENTE = 1
ORDER BY
    REPRESENTANTES.NOME_REP_CLIENTE
     
    


/**
    OBS: 
        TIPO_REPR -> TABELA DE TIPOS DE REPRESEMTANTE : SUSPEITO QUE NÃO EXISTA UM CASE RESOLVE... MAS SE EXISTIR ME FALA
        COD_CIDADE -> CIDADE + ESTADO : basi_160
        COD_BANCO_REPR -> TABELA DE BANCOS
        SIT_REP_CLIENTE -> TABELA DE SITUAÇÃO DE REPRESENTANTE : SUSPEITO QUE NÃO EXISTA UM CASE RESOLVE... MAS SE EXISTIR ME FALA
    DEV: 
        TIAGO DE ABREU | DATE: 17/02/2022 | COMMIT MESSAGE: INICIANDO RELATÓRIO DE REPRESENTANTES 
**/